### DISCUSSION TITLE
Your Kanboard instance is not configured to install plugins from the user interface

### DISCUSSION THREAD

**Discussion by timdonovanuk** [kanboard/kanboard#5186] [Installation & Configuration]
- All the previously closed bug reports on this links to documentation that is now 404
- I have spent 2 mins searching the documentation but cannot see a section on this
- Don't tell users "it's not configured" - empower them to fix it by telling them HOW to configure it
- Why not have this enabled/setup by default? I used docker to install

**Comment by voodoohoo** [comment]
+1
same here. Use latest docker v1.2.20 and cannot install plugins. Found no info what to do to fix it

**Comment by fguillot** [comment]
See https://docs.kanboard.org/en/latest/admin_guide/plugins.html

![image](https://user-images.githubusercontent.com/323546/138534438-c4984c50-37be-4737-840e-24d16367d66d.png)

**Comment by voodoohoo** [comment]
Sure, I know about the gerneral configuration doc.

But what about the docker installation?
I set the config paramter PLUGIN_INSTALLER to true in config.php. Afterwards the plugins are listed ont he web page.
But it is not possible to install any of them: "Your Kanban installation is not configured to install plugins via web interface" 

![image](https://user-images.githubusercontent.com/3798979/138549540-3b844d11-29cc-4b49-8914-eb6215cbc836.png)

What and how has to be configured when using the docker installation?

**Reply by creecros** [reply]
https://github.com/kanboard/kanboard/blob/59a4c7f73bd32e6646cf32331546dd1f6e0c4ead/docker/etc/php81/conf.d/local.ini#L10

The docker container is configured to cache code. So simply changing php code will leaving you scratching your head if you don't take the next step and restart the container.

**Comment by deeagle** [comment]
@voodoohoo Do you link the correct `config.php` in `docker-compose.yml`?

```yml
...
kanboard
  volumes:
  - /local/path/config.php:/var/www/app/config.php:ro
...
```
Because I maped the false one with `config.default.php` (and I do all changes in `config.php`).

After that I have to adapt the permissions to **777**.
Because the permissions of the folder was **755 _apt system-journal**.

**Comment by laundmo** [comment]
I have to agree with OP here, getting this working is quite unintuitive. I would love for this to be easier to set up with docker, by just setting a env var for example. Then, in the docs, make that envvar set to false by default. but set it explicitly. that way just looking at the docker command or compose its obvious what needs to be done.

For example, since i dont know PHP i just put `define('PLUGIN_INSTALLER', true);` in a otherwise empty `config.php` and got this:
![](https://img.laundmo.com/u/Z7TbFj.png)

**Comment by sbn-purchark** [comment]
https://kanboard.discourse.group/t/docker-and-plugins/707/2

He is correct, the changed suggested works.

**Comment by HardlineStudios** [comment]
> https://kanboard.discourse.group/t/docker-and-plugins/707/2
> 
> He is correct, the changed suggested works.

Yeah this worked for me as well.

**Comment by pannet1** [comment]
i am not using docker and i was changing the config.default.php whereas, it should be copying as config.php and the changes should be made there. loved kanboard so far, has the potential to be hacked as the top project management tool with the plugins.

**Comment by fguillot** [comment]
The documentation has been improved. I hope that helps.

- https://docs.kanboard.org/v1/admin/plugins/
- https://docs.kanboard.org/v1/admin/docker/

Docker Compose:

```yaml
version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
     - "8080:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
```

Docker command line:

```bash
docker run --rm \
  --name=kanboard
  -p 8080:80 \
  -e PLUGIN_INSTALLER=true \
  kanboard/kanboard:latest
```
