### DISCUSSION TITLE
Wrong URL in password recovery email

### DISCUSSION THREAD

**Discussion by vitoyucepi** [kanboard/kanboard#5197] [Installation & Configuration]
### Actual behaviour
Password restoration email has wrong url that ignores port.
In my case I'm running kanboard on `http://localhost:8080`. It's a local development version in docker.
URL in email looks like
`http://localhost/forgot-password/change/ea6e1fffe4945e2ff4eae4d4cf0eb52c4224bad171e481cf77e0f1099957c9`

### Expected behaviour

URL in email should look like
`http://localhost:8080/forgot-password/change/ea6e1fffe4945e2ff4eae4d4cf0eb52c4224bad171e481cf77e0f1099957c9`

### Steps to reproduce

`docker-compose`:
```yml
version: "3.8"
services:
  web:
    image: "kanboard/kanboard:${KANBOARD_VERSION}"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    env_file:
      - postgres.env
      - kanboard.env
  db:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    environment:
      TZ: ${TZ}

volumes:
  kanboard_data: {}
  kanboard_plugins: {}
  kanboard_ssl: {}
  db_data: {}
```
`kanboard.env`
```env
MAIL_TRANSPORT="smtp"
MAIL_SMTP_HOSTNAME="${KANBOARD_SMTP_HOSTNAME}"
MAIL_SMTP_PORT="${KANBOARD_SMTP_PORT}"
MAIL_SMTP_USERNAME="${KANBOARD_SMTP_USERNAME}"
MAIL_SMTP_PASSWORD="${KANBOARD_SMTP_PASSWORD}"
MAIL_SMTP_ENCRYPTION="${KANBOARD_SMTP_ENCRYPTION}"
MAIL_CONFIGURATION="false"
MAIL_FROM="${KANBOARD_MAIL_FROM}"
```

1. Provide valid mail settings via env vars
1. Run with `docker-compose up`
1. Login with `admin:admin`
2. Set admin email address
3. Restore email address
4. Email will arrive with wrong restoration address.
    In my case it will look like this

### Configuration

- Kanboard version: v1.2.18
- Database type and version: postgres 13.1-alpine
- PHP version: 7.3 from alpine package repository
- OS: docker run on archlinux
- Browser: Chromium 88
