### DISCUSSION TITLE
Custom config file issue with Docker

### DISCUSSION THREAD

**Discussion by Ixiruss** [kanboard/kanboard#5510] [Installation & Configuration]
Hello,

I have an issue with the config.php file.

I'm currently configuring a docker compose instance of Kanboard.
My docker compose file is : 

```
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./kanboard_data:/var/www/app/data
     - ./kanboard_plugins:/var/www/app/plugins
     - ./kanboard_ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
```

About physical root path (Debian), it is located here /home/kanboard

The website is working very well, I was able to install a plugin, it's visible in ./kanboard_plugins and working.
But I don't understand how the config.php file is working for Docker installation.

1. When I go to ./kanboard_data (/var/www/app/data), I don't see any config.php file nor config.default.php visible. Only db.sqlite

2. Following https://docs.kanboard.org/v1/admin/docker/#custom-config-file, the file should be here from the volume (/var/www/app/config.php).
> The container already includes a custom config file located at /var/www/app/config.php.
I temporarily mounted the volume /var/www/app/ to see if a file was visible, but there is nothing.

3. The doc says :
> You can store your own config file on the data volume: /var/www/app/data/config.php.
So I did it (it was the first thing that I tried to be honest), but the result (container restarted or not) was this : 
But I can see the website totally replaced by the string content of my new config.php file
And multiple lines like this below.
Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/data/config.php:1) in /var/www/app/app/Core/Http/Response.php on line 222

So it means that all necessary files are already located in /var/www/app/data, but I'm not able to see them.

Maybe I have an issue with how my volumes are mounted ?

Thanks for your help
