### ISSUE TITLE
Select columns for public link

### ISSUE THREAD

**Issue by juergenniessen** [kanboard/kanboard#3092]
Feature request:

### Actual behaviour

Public link shows all columns (and all Swimlanes)

### Expected behaviour

It would be great, if the columns (and maybe Swimlanes) were selectable that should be displayed on the public link. 
You could add in addition to "Visible on dashboard" the option "Visible on public link" under  Setting - Columns

### Configuration

Version: 1.0.40
PHP Version: 5.5.9-1ubuntu4.11
PHP SAPI: apache2handler
OS Version: Linux 3.2.0-70-generic
Datenbanktreiber: mysql
Datenbank Version: 5.5.44-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by fguillot** [comment]
Is it really necessary? adding features complexify the software..

**Comment by juergenniessen** [comment]
We have the public link on a large flatscreen and the right two columns only contain closed task, so there is a lot of unused space on the sceeen.

It's a nice2have, but not really necessary.

**Comment by raffaelj** [comment]
@juergenniessen If you just want to hide something on your screen you can use a simple workaround by using custom CSS styles in your browser.

An example for the Firefox-Stylish-Plugin:

```css
@-moz-document url("https://your-public-link-with-long-token") {
  td.board-column-93 {display: none;}
  th.board-column-header-93 {display: none;}
  td.board-column-94 {display: none;}
  th.board-column-header-94 {display: none;}
}
```

Now the columns with the specified IDs aren't visible anymore.

**Comment by raffaelj** [comment]
I found a second and easier solution. You don't even need a plugin. Just use a custom stylesheet inside the kanboard configuration:

```css
.public-board th.board-column-header-94,
.public-board td.board-column-94
{display:none;}
```
