### ISSUE TITLE
Pure CSS Logo Change

### ISSUE THREAD

**Issue by MarcosBL** [kanboard/kanboard#3132]
### Actual behaviour

Logo name is not editable

### Expected behaviour

Being able to change the logo, at least the text

### Steps to reproduce

Just look at the top left

### Configuration

No configuration issue

### Custom CSS to setup a custom logo

````css
h1 > span.logo > a > span {
    margin-left: -15px;
}
h1 > span.logo > a > span:before {
  content: 'My';
  background: #fff;
    color: #041f54;
}
h1 > span.logo > a:after {
  content: 'Proyects';
  margin-left: -15px;
  background: #fff;
  color: #881c01;
}
````

Sample:

![image](https://cloud.githubusercontent.com/assets/389801/24025393/5c76e792-0aba-11e7-8e54-5a2473f2d925.png)
