### ISSUE TITLE
Feature request: Printing/exporting the board view

### ISSUE THREAD

**Issue by rolandkoller** [kanboard/kanboard#3188]
### Actual behaviour

When printing the board view, the output is text only, the board is not visually reproduced.

![screenshot printing](https://cloud.githubusercontent.com/assets/27192481/24857860/0d150bdc-1dea-11e7-98d2-caf4ab2054fd.png)

### Expected behaviour

It would be nice to have the posibility to export (PDF) or print a graphical representation of the board view.

![screenshot board view](https://cloud.githubusercontent.com/assets/27192481/24857861/0d15772a-1dea-11e7-91bb-b4b231a4877f.png)

### Steps to reproduce

Press Ctrl-P in e. g. IE, Firefox in board view

**Comment by tzeumer** [comment]
I think printing does not make to much sense, but some co-workers want to print boards anyway, too. One gets a descent print layout if the style were not explicitly applied for media=screen only. An ugly hack is this

1. Edit {kanboard-folder}\app\Template\layout.php
2. Replace " <?= $this->asset->css('assets/css/app.min.css') ?>" with
```
<!-- Replacement code. Printing hack. Landscape, keep tasks together on page, show overflow -->
<style type="text/css"  media="print">
    @page {
        orientation:landscape;
        -webkit-transform: rotate(-90deg); 
        -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    #board-container { overflow-x: initial !important; }
    .board-task-list { min-height: 0 !important; }
    .task-board      { page-break-inside: avoid; }
</style>
<?= $this->asset->css('assets/css/app.min.css', true, 'screen, print') ?>
<!-- Original code; <?= $this->asset->css('assets/css/app.min.css') ?> -->
```

It's not perfect but works well for a reasonable number of columns. Maybe it helps someone.

**Comment by rolandkoller** [comment]
@tzeumer: Your css workaround is quite good. Thank you!

**Comment by rajo** [comment]
@tzeumer this works very well
@fguillot could this workaround become an official solution?

**Comment by lastlink** [comment]
I might also hide the menu's in the css
```css
@media print {
  /*Hide menu */
  .menu-inline, .project-header, .menus-container { display: none; }
}
```

**Comment by lastlink** [comment]
This is my final hiding menu's from printing. May still need work

```css
@media print {
@page {
        orientation:landscape;
        -webkit-transform: rotate(-90deg); 
        -moz-transform:rotate(-90deg);
        filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
    #board-container { overflow-x: initial !important; }
    .board-task-list { min-height: 0 !important; }
    .task-board      { page-break-inside: avoid; }
   
   /*Hide menu */
  .menu-inline, .project-header, .page-header, .menus-container, .sidebar, .alert, .alert-info, .dropdown > ul  { display: none; }

}
```
