### ISSUE TITLE
Theme semi dark

### ISSUE THREAD

**Issue by Xarkam** [kanboard/kanboard#3708]
Hello, I share with you my css to make a semi dark theme.
```css
body {
    background-color: #333;
}
header {
    border-bottom: 1px solid #333333;
    background-color: #3c8dbc;
}

header h1 {
    color: #fff;
}

.sidebar>ul li {
    border-bottom: 1px dotted #545454;
}

.sidebar-content {
    background-color: #fff;
    border-radius: 3px;
}

.board-swimlane {
    background-color: #f5f5f5;
}

.input-addon-item {
    background-color: #dfdfdf;
}

.sidebar>ul li:hover {
    border-left: 5px solid #3c8dbc;
    background: #1e282c;
}

.sidebar>ul a:hover {
    color: #fff;
}

.sidebar>ul li.active a {
    color: #fff;
}

.dropdown-component .dropdown a.dropdown-menu, .dropdown-component .dropdown a.dropdown-menu i  {
    color: #fff;
}

.accordion-content {
    background: #fff;
}

.accordion-title h3 {
    border-radius: 5px;
}

.notification a i {
   color: #fff;
}

.dropdown.header-creation-menu a i {
    color: #fff;
}

.dropdown a.dropdown-menu.dropdown-menu-link-icon i {
   color: #fff;
}

.page-header a, .menu-inline a {
    color: #6b6b6b;
}

.page-header a:hover, .menu-inline a:hover {
    color: #fff;
}

.form-login {
    background: #fff;
    padding: 25px;
}

.input-addon-item .dropdown .dropdown-menu.dropdown-menu-link-icon i {
    color: #333;
}

.sidebar-content {
    padding-top: 15px;
}

.table-list-row.table-border-left {
    background: #fff;
}

.fc-view.fc-month-view.fc-basic-view{
    background: #fff;
}

#gantt-chart {
    background: #fff;
}

.tooltip .fa-info-circle {
    color: #000;
}

.project-overview-columns {
    background: #fff;
    padding-bottom: 5px;
    border-radius: 5px;
}

.sidebar.sidebar-icons a i {
    color: #a2a2a2;
}

.table-list {
    background: #fff;
}

.dropdown a.dropdown-menu.dropdown-menu-link-icon i.fa.fa-cog.ui-sortable-handle, 
.dropdown a.dropdown-menu.dropdown-menu-link-icon i.fa.fa-caret-down.ui-sortable-handle,
.dropdown a.dropdown-menu.dropdown-menu-link-icon i.fa.fa-cog,
.dropdown a.dropdown-menu.dropdown-menu-link-icon i.fa.fa-caret-down {
    color: #949494;
}

.menus-container .dropdown a.dropdown-menu.dropdown-menu-link-icon i.fa.fa-caret-down {
   color: #fff;
}

.page-header a:hover, .menu-inline a:hover {
    color: #3c8dbc;
}

.sidebar>ul li.active a:focus, .sidebar>ul li.active a:hover {
    color: #3c8dbc;
}
```
### Install
Simply copy and paste the css in custom stylesheet section in application settings.

### Screenshots
![image](https://user-images.githubusercontent.com/331816/36053019-4bdd8690-0df0-11e8-8ade-4a6e25b99f92.png)

![image](https://user-images.githubusercontent.com/331816/36052810-7bb70676-0def-11e8-90e7-acc34ea59454.png)

![image](https://user-images.githubusercontent.com/331816/36052824-8bddc530-0def-11e8-998a-0b4076e201f6.png)

![image](https://user-images.githubusercontent.com/331816/36052895-d8e2795c-0def-11e8-9266-654bda6564fa.png)

### Configuration

- Kanboard version: 1.2.0
- Browser: Chrome

### Not implemented
Border radius for Firefox, Edge and IE
