### ISSUE TITLE
Documentation for Debian 9

### ISSUE THREAD

**Issue by oneyb** [kanboard/kanboard#3927]
The installation documentation for Debian is old. I don't know how to contribute directly to the documentation. 

There is an ansible playbook below that works for debian stretch/9. It sucks. Maybe an ansible pro would like to use it as a building block for other popular Linux systems. 

```yaml
---
# run this: ansible-playbook -i localhost, -u $USER install-kanboard.yaml --ask-become-pass
- hosts: all

  vars:
    version: 1.2.5
  tasks:
  - name: install necessary packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=86400
    become: yes
    with_items:
      - apache2
      - libapache2-mod-php7.0
      - php7.0-cli
      - php7.0-mbstring
      - php7.0-sqlite3
      - php7.0-opcache
      - php7.0-json
      - php7.0-mysql
      - php7.0-pgsql
      - php7.0-ldap
      - php7.0-gd
      - php7.0-xml

  - name: unzip/install kanboard
    get_url:
      url: "https://github.com/kanboard/kanboard/archive/v{{ version }}.tar.gz"
      dest: "{{ ansible_env.HOME }}/bin/src/kanboard-{{ version }}.tar.gz"

  - name: unzip/install kanboard
    unarchive:
      # could supply the URL directly but debugging is slower and I don't want
      # root accessing the internet...
      src: "{{ ansible_env.HOME }}/bin/src/kanboard-{{ version }}.tar.gz"
      dest: /var/www/html
    become: yes

  - name: set ownership
    file:
      dest: /var/www/html/data
      owner: www-data
      group: www-data
      recurse: yes
    become: yes

  - name: start apache2
    systemd: name={{ item }} state=restarted enabled=yes
    become: yes
    with_items:
      - apache2
      - postgresql
```
