### ISSUE TITLE
Maximize screen real-estate: not show column titles on each swimlane?

### ISSUE THREAD

**Issue by amca01** [kanboard/kanboard#3994]
I hope the topic makes my query clear.  I am trying to plan a semester's teaching using each column for a week, and swimlanes including titles such as "Pre-reading", "Topics", "In class activities", "Assessment" and so on.  The only trouble I have is that when I look at the entire board, there's a lot of wasted space in that the heading of each column is repeated above each swimlane.  Is there any way of turning these headings off (except for the first swimlane)?

Or, if there's some sort of "grid view" of the board which shows the column titles above each column, and the swimlane titles to the left, sort of like a spreadsheet?

Thanks very much!

**Comment by Qrizzz** [comment]
You could try adding something like this to your custom stylesheet

```css
tr[class*='board-swimlane-columns']:not(:first-child) {
    display: none;
}
```

**Comment by Qrizzz** [comment]
If you miss the functionality of the titles (add tasks, number of tasks …) you could restore via Mouse hover over the swimlane title (needs some tweeking because it jumps arround

```css
tr[id*='swimlane']:hover + tr[class*='board-swimlane-columns'],
tr[class*='board-swimlane-columns']:hover {
    display: table-row!important;
}
```
