### ISSUE TITLE
Kanboard with Docker don't run!

### ISSUE THREAD

**Issue by jhonatams** [kanboard/kanboard#4138]
Hi,
This issue is:

- [X] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour

I'm trying run Kanboard with Docker.
When I run using only sqlite database the container run normaly.

### Expected behaviour

But when I try run using mysql/mariadb database occour some problems.

### Steps to reproduce

In my database MariaDB:

CREATE DATABASE kanboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALTER, CREATE, DELETE, DROP, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON kanboard.* TO 'kanboard'@'%';

FLUSH PRIVILEGES;

Run docker image with next params(I use kubernetes to deploy):

[root@my-host files]# vi kanboard.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanboard
  labels:
    app: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
    spec:
      containers:
        - name: kanboard
          image: kanboard/kanboard:v1.2.8
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /var/www/app/data
              name: kanban-storage
              subPath: ./var/www/app/data
            - mountPath: /var/www/app/plugins
              name: kanban-storage
              subPath: ./var/www/app/plugins
          env:
            - name: DEBUG
              value: 'true'
            - name: DATABASE_URL
              value: 'mysql://kanboard:my-password@infra-mariadb:3306/kanboard'
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1Gi
              cpu: 2
            requests:
              memory: 128Mi
              cpu: 0.25
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: kanban-storage
          persistentVolumeClaim:
            claimName: kanban-storage-pvc
```

Creating the container:
[root@my-host files]# kubectl create -f vi kanboard.yaml

Access from browser https://kanboard.my-site.com.br

Internal Error: Unable to run SQL migrations: Running migration \Schema\version_129, SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'name' used in key specification without a key length (You may have to fix it manually)

To solve the problem I try:
According the issue https://github.com/kanboard/kanboard/issues/3880 I executed:

```
ALTER TABLE projects DROP INDEX name_3;
ALTER TABLE projects DROP INDEX name_4;
```
But later that I executed the commands above, I received:

Internal Error: Unable to run SQL migrations: Running migration \Schema\version_129, Running migration \Schema\version_130, Running migration \Schema\version_131, Running migration \Schema\version_132, SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'color_id' (You may have to fix it manually)

So I jumped this migrations executing the next update, and the application run!
```
update schema_version set version = 133;
```

But my question is:
Why I have to do all this to run Kanboard with docker?
Some problem exists with the creation of container Docker of Kanboard!
This is the right way to fix this problem, or is necessery change some code to up a container without errors?

* I have tested the versions v1.2.7 and v1.2.8 the same problem occour in the both.

I'll be grateful for the help.

### Logs

Nothing is showing when I consult the logs.

[root@my-host files]# kubectl logs -f kanboard-54f41dc489-fjkml
```
Generating a RSA private key
................................+++++
........................................+++++
writing new private key to '/etc/nginx/ssl/kanboard.key'
-----
```

### Configuration

- Kanboard version: v1.2.7 or v1.2.8 the same problem occour
- Database type and version: MariaDB 10.3.11-MariaDB-1:10.3.11+maria~bionic mariadb.org binary distribution
- PHP version: PHP 7.2.13 (from docker pull kanboard/kanboard:v1.2.8)
- OS: Alpine Linux v3.8.1 (from docker pull kanboard/kanboard:v1.2.8)
- Browser: Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by fguillot** [comment]
Trying this locally, I do not have this problem with MariaDB 10.3 or MySQL 8.

Here an example of `docker-compose.yml`:

```
version: '2'
services:
  kanboard:
    image: kanboard/kanboard:v1.2.8
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kb:kb-secret@db/kanboard
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kb
      MYSQL_PASSWORD: kb-secret
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
```

- You can also try to load the schema manually, see https://docs.kanboard.org/en/1.2.8/admin_guide/mysql.html#importing-sql-dump-alternative-method
- Or, run the migrations manually: https://docs.kanboard.org/en/1.2.8/admin_guide/upgrade.html#running-sql-migrations-manually

If you still have installation issues, please use the forum: https://kanboard.discourse.group/
