### ISSUE TITLE
Inconsistence with hovering icon color on dropdown menus

### ISSUE THREAD

**Issue by rafacamargo123** [kanboard/kanboard#4167]
### Actual behaviour

Some dropdown itens change their icon color to white when the option is hovered, some don't

### Expected behaviour

Most options keep black, but would be better if all icons changed their color to white, like the text, when hovered

I found the cause:
When the icon element (`<i>`) is inside the `<a>` link, it does not change its color when hovered. However, when its inside the `<li>` element, on the same level as the `<a>` element, it changes the color.
I don't know how to fix this on the source codes, but I managed to fix it with this css:

```css
.dropdown-submenu-open li:not(.no-hover):hover .fa {
    color: white;
}
```

The css that is applied when the icon is directly inside an `<li>` hovered is:
```css
.dropdown-submenu-open li:not(.no-hover):hover {
    background: #4078C0;
    color: #fff;
}
```
It does not apply when the li element is hovered because a more specific rule is defined before it:
```css
a .fa {
    padding-right: 3px;
    text-decoration: none;
    color: #333;
}
```
### Steps to reproduce

Just open some dropdown menus and hover some options. Examples:
Board header cog > collapse tasks  = icon is black
Board header cog > compact view   = icon is white when hovered

Profile photo dropdown > settings = icon is black
Profile photo dropdown > documentation = icon is white when hovered

### Screenshots

![image](https://user-images.githubusercontent.com/12586009/55255360-38bc7880-5239-11e9-8773-a33b43772c0c.png)
![image](https://user-images.githubusercontent.com/12586009/55255368-3fe38680-5239-11e9-97be-e46aae97da5d.png)
![image](https://user-images.githubusercontent.com/12586009/55255386-4d990c00-5239-11e9-85bd-e48ced4c39f2.png)
![image](https://user-images.githubusercontent.com/12586009/55255395-5558b080-5239-11e9-94ce-8a619e55ae06.png)

### Configuration

- Kanboard version: 1.2.8
