### ISSUE TITLE
DATABASE_URL not taken into account

### ISSUE THREAD

**Issue by doc75** [kanboard/kanboard#4236]
# Actual behaviour

When using docker image with DATABASE_URL set, it appears that sqlite database is always used (cf. info in Settings)

### Expected behaviour

I am expecting to have the proper database set in DATABASE_URL used in Settings.

### Steps to reproduce

* create directory (e.g.: kanboard)
* in this directory, create a `.env`file with the following content:

```shell
POSTGRES_PASSWORD=MyStrongPassword
DATABASE_URL=postgres://kanboard:MyStrongPassword@db:5432/kanboard
```

* create also a `docker-compose.yml` file with the following content:

```yaml
---
version: '3'
services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
    - POSTGRES_DB=kanboard
    - POSTGRES_USER=kanboard
    env_file:
    - ".env"
    volumes:
    - "${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-kanboard}/db:/var/lib/postgresql/data"
    - "./sql/postgres.sql:/docker-entrypoint-initdb.d/initdb.sql"
  app:
    image: kanboard/kanboard:latest
    restart: unless-stopped
    environment:
    - ".env"
    volumes:
    - "${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-kanboard}/app/data:/var/www/app/data"
    - "${CHATONS_ROOT_DIR:-/srv/chatons}/${CHATONS_SERVICE:-kanboard}/app/plugins:/var/www/app/plugins"
    ports:
      - "80:80"
      - "443:443"
    networks:
    - default

```
* create a `sql` directory
* inside the `sql` directory, copy the file from Kanboard repo `kanboard/app/Schema/Sql/postgres.sql`

### Screenshots

None

### Logs

None

### Configuration

- Latest docker image
- Browser: Firefox

I am ready to help debugging, but to be honest, I tried to put traces in the code inside the docker container (and even to add DEBUG=true), but I was not able to see my traces.
Do not hesitate to let me know if more information would be needed, I would be more than happy to help.
