### ISSUE TITLE
Security http headers are not adjustable

### ISSUE THREAD

**Issue by vitoyucepi** [kanboard/kanboard#4730]
### Actual behaviour

Each http header has ability to disable some security headers by config options.
```php
// Enable or disable "Strict-Transport-Security" HTTP header
define('ENABLE_HSTS', true);

// Enable or disable "X-Frame-Options: DENY" HTTP header
define('ENABLE_XFRAME', true);
```

But other security headers are not switchable
```http
Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src * data:;
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

### Expected behaviour

I want to disable this headers by config variables.
The config variables may look like
```php
define('ENABLE_CSP', true);
define('ENABLE_SECURITY_HEADERS', true);
```

### Steps to reproduce

`docker-compose`:
```yml
version: "3.8"
services:
  web:
    image: "kanboard/kanboard:${KANBOARD_VERSION}"
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    env_file:
      - postgres.env
      - kanboard.env
  db:
    image: "postgres:${POSTGRES_VERSION}"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - postgres.env
    environment:
      TZ: ${TZ}

volumes:
  kanboard_data: {}
  kanboard_plugins: {}
  kanboard_ssl: {}
  db_data: {}
```
`kanboard.env`
```env
ENABLE_HSTS=false
ENABLE_XFRAME=false
```

1. Run with `docker-compose up`
2.
    * Browser variant
      1. Open `http://localhost:8080`
      2. Open developer tools
    * Cli variant
      1. Run `curl http://localhost:8080`
      2. Look for security headers
          ```sh
          curl -s -I http://localhost:8020 | grep -P '(X-Content-Type-Options|X-XSS-Protection|Content-Security-Policy)'
          ```

### Configuration

- Kanboard version: v1.2.18
- Database type and version: postgres 13.1-alpine
- PHP version: 7.3 from alpine package repository
- OS: docker run on archlinux
- Browser: Chromium 88
