### ISSUE TITLE
Got "Internal Error: Database driver not supported" when I try launch Kanboard with docker container

### ISSUE THREAD

**Issue by skyhos** [kanboard/kanboard#4930]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Overview
With official MariaDB and official Kanboard docker images, I've tried to run Kanboard by docker compose. However, it shows only "Internal Error: Database driver not supported" message when I visit Kanboard homepage.

### Actual behaviour
When I visit kanboard endpoint it shows "Internal Error: Database driver not supported" error message.

### Expected behaviour
It shows me the kanboard homepage.

### Steps to reproduce
 I've also created the MariaDB user and database for Kanboard and given the user full permissions for the database.

run docker-compose with following configurations.
```
# cat docker-compose.yaml
version: "3.0"
networks:
  net1: {}
services:
  mariadb:
      container_name: mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=mariadb_password
      image: mariadb:latest
      networks:
        net1:
          aliases:
            - mariadb
      ports:
        - 3306:3306
      volumes:
        - /myvolume/mariadb/my.cnf:/etc/mysql/my.cnf
        - /myvolume/mariadb/data/mariadb:/var/lib/mysql
        - /myvolume/mariadb/logs/mariadb:/var/log/mysql
      user: "1000:1000"

  kanboard:
      container_name: kanboard
      environment:
        - DATABASE_URL= mysql://kanboard:kanboard-secret@mariadb/kanboard
      image: kanboard/kanboard:latest
      networks:
        net1:
          aliases:
            - kanboard
      volumes:
        - /myvolume/kanboard/data:/var/www/app/data
        - /myvolume/kanboard/plugins:/var/www/app/plugins
      depends_on:
        - mariadb
```

```
# cat /myvolume/kanboard/data/config.php
<?php

defined('DB_DRIVER') or define('DB_DRIVER', 'mysql');
defined('DB_USERNAME') or define('DB_USERNAME', 'kanboard');
defined('DB_PASSWORD') or define('DB_PASSWORD', 'kanboard-secret);
defined('DB_HOSTNAME') or define('DB_HOSTNAME', 'mariadb');
defined('DB_NAME') or define('DB_NAME', 'kanboard');

defined('PLUGIN_INSTALLER') or define('PLUGIN_INSTALLER', true);
```

### Logs
```
# docker logs -f kanboard
Generating a RSA private key
...........................+++++
..+++++
writing new private key to '/etc/nginx/ssl/kanboard.key'
-----
```

```
# docker image inspect mariadb:latest
[
    {
        "Id": "sha256:eff629089685eb7051a239d4217f334580c09e557a9ecfeb2d562a1229d10e7f",
        "RepoTags": [
            "mariadb:latest"
        ],
        "RepoDigests": [
            "mariadb@sha256:0c3c560359a6da112134a52122aa9b78fec5f9dd292a01ee7954de450f25f0c1"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-05-25T01:32:04.00297519Z",
        "Container": "3d01b82bbb64a4631cc68daf71075edba9b73b75df638b53aba0036a2573e36c",
        "ContainerConfig": {
            "Hostname": "3d01b82bbb64",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.12",
                "GPG_KEYS=177F4010FE56CA3336300305F1656F24C74CD1D8",
                "MARIADB_MAJOR=10.5",
                "MARIADB_VERSION=1:10.5.10+maria~focal"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"mysqld\"]"
            ],
            "Image": "sha256:5181f86c1db2dd296870da20c4d5df35e6f5a3de236c584aa58df4d60a8517a2",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "19.03.12",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.12",
                "GPG_KEYS=177F4010FE56CA3336300305F1656F24C74CD1D8",
                "MARIADB_MAJOR=10.5",
                "MARIADB_VERSION=1:10.5.10+maria~focal"
            ],
            "Cmd": [
                "mysqld"
            ],
            "Image": "sha256:5181f86c1db2dd296870da20c4d5df35e6f5a3de236c584aa58df4d60a8517a2",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 407555827,
        "VirtualSize": 407555827,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/7610166dd81322dec064ccb716da34062871ebf75f4191230737090cd0d196a0/diff:/var/lib/docker/overlay2/3c1b84ae785d6eefb5b8782ee4486714659fbcf292468a9787c65473299aff2e/diff:/var/lib/docker/overlay2/e3865900cc51ecd055b162deec8f57f3abfd0018686be5c7bb2cadb356e77060/diff:/var/lib/docker/overlay2/f985dd26ee3abfcb628cc10ccc0054dfda9738d2ec14651199b17d7fc25ac52d/diff:/var/lib/docker/overlay2/f2719f94211ccde54ee115e8ee44389b8462ce2598e0022f88368d6c50cc2668/diff:/var/lib/docker/overlay2/3303f62f0b9407f6c2cd9675814b9b22a1efd958b82abb55d1e28dfa1f54e391/diff:/var/lib/docker/overlay2/7a4fa25b4aa034e34137755d5044fd1052f4a8497452fef0aa6589a35a64eef3/diff:/var/lib/docker/overlay2/0a690fa7a8ae73f0de10557b30c258ea0ee7675fcbb2afd3c41273dd984e73a8/diff:/var/lib/docker/overlay2/3714b7b3ad753a606e6866e755a5f4ede98d99fd6ec66569745cd3e95947cb06/diff:/var/lib/docker/overlay2/6726497b34024592433ec38e32f7546adfda2f80c202eba70c519a786f960f40/diff:/var/lib/docker/overlay2/a345b39fc91109ecd826a91dbef9077beedab78fa25d9a90d541461d09d18f22/diff",
                "MergedDir": "/var/lib/docker/overlay2/db6e892c49b0f061923d794ab8ab58d0c160bd7b377d22376bc6370fd16f0bd7/merged",
                "UpperDir": "/var/lib/docker/overlay2/db6e892c49b0f061923d794ab8ab58d0c160bd7b377d22376bc6370fd16f0bd7/diff",
                "WorkDir": "/var/lib/docker/overlay2/db6e892c49b0f061923d794ab8ab58d0c160bd7b377d22376bc6370fd16f0bd7/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:ccdbb80308cc5ef43b605ac28fac29c6a597f89f5a169bbedbb8dec29c987439",
                "sha256:63c99163f47292f80f9d24c5b475751dbad6dc795596e935c5c7f1c73dc08107",
                "sha256:2f140462f3bcf8cf3752461e27dfd4b3531f266fa10cda716166bd3a78a19103",
                "sha256:3c9e9fb59a80b8e34e71cae9c0bd1a6cc7765db296dc6f695415ec37a5fccf6d",
                "sha256:304f67bded890973179af3d4e05a7e58019980cd07335d1e9be85f392309be8c",
                "sha256:5dbb97db08f29d07d9c214bd22992435882df3045f34cc91932f4e58f61c1ee4",
                "sha256:fc94e5730a4215d7c6f4167c950b63034cf1bb42b97ca363d775130ad17d583b",
                "sha256:3571840565580d153f42700727d5e7df8c52a610d73e9dd5fecdc6c5a2b37b48",
                "sha256:7883e2cbb0ab8addf076a2f0eb020711d090df4108d52824c4e748370a0cbbc0",
                "sha256:b903d694000eb510e848d95ebfd086a2de973eda730247e2843e19d02a6db9fb",
                "sha256:51f1b181444cd90de06996ec9dbb5623937021d0026c8daed4764b4b9119a9ba",
                "sha256:f282d4e95dfda610a7d9f38ac811dcee41a9d752f6ca1266c712c2b2cac08e61"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
### Configuration

- Kanboard version: latest docker of official Kanboard 
- Database type and version: Official MariaDB docker, please, refer to the image inspection of Logs section above.
- PHP version: using Kanboard's latest docker
- OS: The docker host is Centos 7
- Browser: Chrome latest version.
