### ISSUE TITLE
Session object destruction failed

### ISSUE THREAD

**Issue by Commiccannon** [kanboard/kanboard#5268]
### Checklist

- [x ] I verified that Kanboard is correctly installed
- [x ] I verified that the problem does not come from a plugin
- [x ] I verified that the problem is not already reported
- [x ] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

Warning: session_regenerate_id(): Session object destruction failed. ID: user (path: ) in /var/www/app/app/Core/User/UserSession.php on line 48
I cannot move tasks around, cannot recreate a new user or anything.

### Expected behaviour

No errors and the ability to use the program

### Steps to reproduce
After a shutdown (Potentially unscheduled, i had a power loss and while i think the UPS gives windows a shutdown signal i want around to ensure it did), restart the computer and kanboard and now i cannot change anything and get the error. I have attempted to remove the container along with all the volumes created for kanboard and am still getting this error

### Logs
[_kanboard-kanboard-1_logs.txt](https://github.com/kanboard/kanboard/files/11570051/_kanboard-kanboard-1_logs.txt)

### Configuration

- Kanboard version: v1.2.29
- Database type and version: whatever the default docker-compose.yml file creates - If you know how to find this and need it i will find it
- PHP version: whatever the default docker-compose.yml file creates - If you know how to find this and need it i will find it
- OS: Windows
- Browser: All

**Comment by javiermolina1234** [comment]
I am able to reproduce this by:
- logging in with the "remember me" checkbox enabled
- closing all browser windows
- reopening the browser and opening my instance of Kanboard

The first visit to Kanboard with the new browser window will show the warning about session object destruction failed.

Environment: docker-compose, kanboard:v1.2.29, volumes as bind mounts instead of managed volumes

```
version: '2'
services:
  kanboard:
    image: kanboard/kanboard:v1.2.29
    ports:
      - "<masked ip>:<external port>:80"
      - "<masked ip>:<external port>:443"
    volumes:
      - ./data/kanboard_data:/var/www/app/data
      - ./data/kanboard_plugins:/var/www/app/plugins
      - ./data/kanboard_ssl:/etc/nginx/ssl
    environment:
      - PLUGIN_INSTALLER=true
    restart: unless-stopped
```
No changes at all to config.php. Removed all plugins and the issue is still reproduceable.
